export const initialState = () => ({
    sessionCode: '',
    createSessionCodeLoading: false,
    createSessionCodeFailure: false,
    createSessionCodeSuccess: true,
    user: {},
    loginLoading: false,
    loginFailure: false,
    loginSuccess: true,
    signupLoading: false,
    signupFailure: false,
    signupSuccess: true,
    updateProfileLoading: false,
    updateProfileFailure: false,
    updateProfileSuccess: true,

    sendOtpLoading: false,
    sendOtpFailure: false,
    sendOtpSuccess: true,
});
